version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - dns_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: $TZ
      WEBPASSWORD: $WEBPASSWORD
      FTLCONF_LOCAL_IPV4: $PIHOLE_IP
      # Configure Pi-hole to use DNSCrypt proxy for DNS resolution
      PIHOLE_DNS_: "127.0.0.1#5354"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    ports:
      - "5354:5354/udp" # Expose DNSCrypt proxy on port 5354
    volumes:
      - './dnscrypt-proxy/config/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml'
    command: "-config /etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    networks:
      - dns_network
    restart: unless-stopped

networks:
  dns_network:
    driver: bridge

